### ISSUE TITLE
3 issues with readme file

### ISSUE THREAD

**Issue by mahammadvaliyev** [rsyamil/gradient-based-hm#3]
1) Why did you write G' instead of G in Loss function equation?

2) Should not  m (solution - argmin L) be (G*G')^(-1)*G*d?

3) In update equation mk+1=...  why do you add the update term, instead of substracting? Should not it be - (corresponding to going in the opposite direction of steepest ascent (gradient)) when we are minimizing the objective function? 

I have also potential suggestions:

1) As all of other methods solve least squares problem,  may be better title for the linear least squares solution would be analytical solution, do not you think so?

2) May be it would good to add elaboration for the gradient term calculation for AE part

**Comment by rsyamil** [comment]
1/2. Check the dimension of G and m, the equations are written based on the dimension of the variables for consistency. 
3. The term $\alpha$ can be negative or positive

1. I think LLS is more descriptive compared to "analytical solution" and is the standard term in history matching
2. I have an open issue for this #2
